### ISSUE TITLE
Manage Users

### ISSUE THREAD

**Issue by jadiaz** [Microsoft/azure-devops-cli-extension#102]
CLI should have the ability to add/remove users (Basic, Stakeholders)

**Comment by EmFl** [comment]
Hello, 
would it be possible to have some info on when this is going to be made available in cli? 
Thanks!

**Comment by geverghe** [comment]
@EmFl we are working on a few other items and should be able to get to this by Feb, 2019 as per plan. I will provide an update in case there is a change in plan. Feel free to make a contribution and we can guide you in case you run into any issues.

**Comment by geverghe** [comment]
Here is the spec against which we are actively developing the user management commands:

| Scenario | Command | Comments/Questions|
|--|--|--|
| As an admin, I want to add a new user to my organization| `az devops user add --user-id` | 1. Why is the verb add when we have had create everywhere? <br> Since this is not actually creating a user, the verb now gives a wrong connotation to intent. It affects uniform commanding but making it create threatens intent. Need to do additional validation on this.| 
| As an admin, I want to remove a user from my organization.| `az devops user remove --user-id` | |
| As an admin, I want to view all users in the organization| `az devops user list` | |
| As an admin, I want to update the access version for a user | `az devops user update --user-id --access-level` | |
| As an admin, I want to view the details pertaining to a user | `az devops user show --user-id ` | |

Would love to hear your thoughts on this

**Comment by ishitam8** [comment]
This is available in version 0.4.0. Hence, closing this.
