### ISSUE TITLE
VSTS instance name is not used in 'work item show' command, even after instance was given at login

### ISSUE THREAD

**Issue by mjalas** [Microsoft/azure-devops-cli-extension#261]
I specified token and instance arguments when logging in, but still I need to specify instance when executing the following command:
```
vsts work item show --id <some_existing_id>
```
The argument '--instance' is not specified as a required argument in the help documentation for show command, as seen below:
```
Command
    vsts work item show : Show details for a work item.

Arguments
    --id [Required] : The ID of the work item.
    --detect        : When 'On' unsupplied arg values will be detected from the current working
                      directory's repo.  Allowed values: off, on.
    --instance -i   : The URI for the VSTS account (https://<account>.visualstudio.com) or your TFS
                      project collection.
    --open          : Open the work item in the default web browser.

Global Arguments
    --debug         : Increase logging verbosity to show all debug logs.
    --help -h       : Show this help message and exit.
    --output -o     : Output format.  Allowed values: json, jsonc, table, tsv.  Default: json.
    --query         : JMESPath query string. See http://jmespath.org/ for more information and
                      examples.
    --verbose       : Increase logging verbosity. Use --debug for full debug logs.
```
The error message does give advice on how to set default instance. 
```
--instance must be specified. The value should be the URI of your VSTS account, for example: https://<account>.visualstudio.com or your TFS project collection. You can set a d
efault value by running: vsts configure --defaults instance=https://<account>.visualstudio.com. For auto detection to work (--detect on), you must be in a local Git directory
that has a "remote" referencing a VSTS or TFS repository.
```
However, this does not make the command-line interface very user friendly. Also, I have not found any documentation that advises a user to set a default instance, even though user only logs in to one single instance.

**Comment by atbagga** [comment]
@mjalas Thanks a lot for feedback! 

I agree adding this info in the [getting started ](https://docs.microsoft.com/en-us/cli/vsts/get-started?view=vsts-cli-latest) would have helped. 

As you found out from the error message --default instance can be specified, which is why instance is not a required parameter in the command. 
If you are inside a git repository path in your terminal, instance, project and repository can also be detected from the git remote url.

**Comment by mjalas** [comment]
@atbagga are the supported default keys documented somewhere? At least I wasn't able to find any that would have included the 'instance' key. The help text for --default option for the configure command only mentioned a couple of keys.

**Comment by atbagga** [comment]
@mjalas Supported default keys are instance, project and output (for output format). 
I have raised a PR to add it to help text explicitly and also in docs. 

Thanks for your feedback.

**Comment by atbagga** [comment]
@geverghe  Please take a look at this requirement/feedback.

I have taken care of the documentation and help text update. 

The other confusion here and in one other reported issue was regarding the use of login instance to be used in commands as default instance since there is single login. 

e.g. A user executes -
vsts login --instance <Organization url> --token <PAT token>
and then expects that the organization url will be auto-detected from login in all future commands.

**Comment by geverghe** [comment]
@mjalas - would the following help-

vsts login --instance --token : this logs you into the instance and checks if there is a default instance. If there is no default instance set, the login instance will be set as default instance. If there is an instance already set, then post login to change is made to defaults.

vsts logout : This will log out the user from all instances. In case a user wants to logout from a specific instance, then use vsts logout --instance.

**Comment by geverghe** [comment]
@mjalas thank you for your contribution!

**Comment by ishitam8** [comment]
Logout for all organizations is supported now.  Refer  #350
