### ISSUE TITLE
Feature Request: Support installation on non-interactive environment

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/azure-devops-cli-extension#421]
Right now, when I run `./cli-install`, the script is waiting for user input.  Please provide flags that will allow us to run this without additional interaction.

## Use Case
- I'm trying to use this in ADO build but can't because this require interaction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29493ec8-b119-457b-21c1-348a6b807884
* Version Independent ID: bf64c389-7811-b33c-6c2a-b8d69a9ec7d3
* Content: [Install the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest)
* Content Source: [latest/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/install.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by atbagga** [comment]
The Azure CLI with the Azure DevOps extension has replaced the VSTS CLI. The VSTS CLI has been deprecated and will no longer be receiving new features. We recommend that users of the VSTS CLI switch to the Azure CLI and add the Azure DevOps extension.

This issue will no longer be a concern since Azure-CLI and Azure DevOps extension install can be done non-interactively. 

Let us know if that solves your problem.

**Comment by mydiemho** [comment]
we should update documentation to remove reference to VSTS CLI.  I  didn't know about VSTS CLI until I was "told" to use it when setting up Feed in ADO Artifacts

![screen shot 2019-02-06 at 2 54 26 pm](https://user-images.githubusercontent.com/1634185/52380634-62b8a200-2a23-11e9-806f-049f2c562582.png)

**Comment by atbagga** [comment]
@mydiemho  Thank you for the feedback. 

The documentation update is planned to happen soon (cc: @geverghe since he is tracking it. )

We did update the VSTS CLI documentation [here](https://docs.microsoft.com/en-us/cli/vsts/overview?view=vsts-cli-latest).

I will go ahead and close this issue. Feel free to open a new bug/feature request in this repo if you face any issue in using Azure DevOps Extension.
