### ISSUE TITLE
Branch Policy Configuration

### ISSUE THREAD

**Issue by smpilo** [Microsoft/azure-devops-cli-extension#432]
Branch Policy Management

Would like to see a set of commands to manage branch policies. This would allow us to script branch policy to conform to team standards. We currently have about 110 git repos internally and want to apply certain policies across the board.

**Comment by snankani** [comment]
@smpilo 
I am happy to share that we recently finished the work to add policy commands to Azure DevOps CLI extension. 
Issue #317 
PR     #379 

New policy command will enable users to add below branch policies -
1. ApproverCountPolicy
2. BuildPolicy
3. CommentRequirementsPolicy
4. MergeStrategyPolicy
5. FileSizePolicy
6. WorkItemLinkingPolicy
7. RequiredReviewersPolicy

It would be good if you can take a look at the command and its options and confirm if the new policy command can help you automate your use cases to apply branch policies on multiple git repos.

https://github.com/Microsoft/azure-devops-cli-extension/issues/317#issuecomment-456043900

**Comment by smpilo** [comment]
certainly looks like it will, looking forward to version release which includes this...

**Comment by gauravsaralMs** [comment]
@smpilo : In case you are interested you can try out the policy commands under development using the edge builds
`az extension add --source https://azuredevopscli.blob.core.windows.net/azuredevopscli/azure_devops-0.3.0-py2.py3-none-any.whl  -y`
you can start with
`az repos policy -h`

Please do provide feedback if any

**Comment by geverghe** [comment]
@smpilo : We have ventured out with a current command approach for policy that lets you manage all repo policies. However, IMO, the create/update experience is a touch difficult due to reliance on doc to understand the right combo of inputs to be keyed in. Would love to hear your thoughts on this - whether it is a pain or whether it is a non issue.

To ease the create experience pain, I am proposing a slight change in command structure. There were different approaches we looked at and we are closing in on the approach highlighted in the table below.


### Reasoning behind approach on command structure.

|| Approach 1: Single policy command to tackle all branch policy types | Approach 2: Policy command sub groups to tackle various policy types| Approach 3: Different policy commands for various policy types | 
|--|--|--|--|
|Commands| az repos policy create/update/list/delete/show | az repos policy list/show/delete <br> az repos policy approver-count create/update <br>az repos policy build create/update <br> az repos policy merge-strategy create/update <br> az repos policy required reviewer create/update <br> az repos policy file-size create/update| az repos approver-count-policy create/update/delete/list/show <br> az repos build-policy create/update/delete/list/show <br> az repos merge-strategy create/update/delete/list/show<br> az repos reviewer-policy create/update/delete/list/show<br> az repos file-size-policy create/update/delete/list/show  |
| Major Scenario 1: I want to create a policy | Moderate-difficult experience since reliance on heavy documentation read through to key in the right combination of inputs for particular policy type. Have a look at the section after the table to view the parameter combos required for the various policy types. | Easy experience since create and update have been segregated based on group and therefore have to deal with only parameters applicable for a particular policy type. | Easy experience since all commands are scoped to a particular policy type. |
| Major Scenario 2: I want to view all policies in my project | Easy experience since policy is treated as a singular concept and therefore achieved through az repos policy list | Easy experience since policy is treated as a singular concept and therefore achieved through az repos policy list | Difficult experience since the view is obtained by running 5 different commands and then collating the results to have a net view of things in project |  
|Summary | Rejected due to difficult create experience | Current Approach | Rejected due to difficult view approach | 
 
### Parameters Required to Create various policy types:
Branch - mandatory if policy is not configured via policy config file..
Policy configuration file: Meta data in file used to configure policies at scale. Required if policy is configured via configuration file. Refer <help doc> on creating a policy config file to create policies.
Detect
is-blocking - Whether blocking or not. Required if policy is not configured using a config file.
is enabled - Whether blocking or not. Required if policy is not configured using a config file.
policy type - Approver count policy, Build policy, file size policy arguments, merge strategy, required reviewers
project - Name or ID of the project. Mandatory if policy is not configured via policy config file or if not set in az devops defaults. 
repo: Name or ID of the repo. Mandatory if policy is not configured via policy config file or if value is not set in az devops defaults. 
organization: Name or ID of the organization. Mandatory if policy is not configured via policy config file or if not set in az devops defaults. 

**Approver Count policy** The following parameters are mandatory if policy type is Approver Count Policy.
Allow Down votes: Whether to allow down votes or not.
Creator vote counts: Whether creator vote counts or not.
Minimum approver count: Min approver count - example --min 2
Reset on Source Push: Whether to rest on source push.

**Build Policy** The following parameters are mandatory if policy type is Build Policy.
Build definition ID
Display Name
Manual Queue only
Queue on source update only
Valid duration

**File Size Policy Arguments** The following parameters are mandatory if policy type is File Size Policy.
Maximum Git Blob size in bytes
Use uncompressed size

**Merge Strategy**The following parameters are mandatory if policy type is Merge Strategy.
Use squash merge

**Required Reviewrs** The following parameters are mandatory if policy type is Required Reviewers.
Message
Optional Reviewers
Required Reviewers
