### ISSUE TITLE
Downloadable .zip version of VSTS CLI for Windows

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/azure-devops-cli-extension#83]
Create efficient (< 15 MB) standalone VSTS CLI .zip for Windows. This will make it easier to use the VSTS CLI from other build tools and services that don't allow installing MSIs.

**Comment by jwittner** [comment]
A chocolatey package would be awesome!

**Comment by flcdrg** [comment]
I've created a Chocolatey package here - https://chocolatey.org/packages/vsts-cli

Let me know if you'd like to take it over, for publishing it directly from your CI/CD pipeline

**Comment by geverghe** [comment]
@willsmythe - out of curiosity, do you have an example of a build system that does not allow msi install?

**Comment by willsmythe** [comment]
I don't recall the scenario that triggered this issue. It's probably safe to say this hasn't been a major problem or else we would have seen more asks for it. The other motivation here was to improve install time during CI since a regular user waiting a few minutes for the CLI to install on their local machine isn't a huge deal (since it's a one-time thing), but a 2-3 minute "tax" every build adds up.

**Comment by geverghe** [comment]
Right, makes sense. To counter the build set up time, we are working on adding the Azure DevOps extension in all hosted pool images. This should cut down the build times as the extension would be pre-baked. However, for users trying to target Azure DevOps from external build systems, the problem is that they now need to install Azure CLI which is ~347 MB. There is an issue https://github.com/Azure/azure-cli/issues/7387 the team is monitoring to reduce package size.
